version: '3.1'

services:
    frontend:
        build:
            context: .
            dockerfile:
                DigiProdVueWebUI/Dockerfile
        ports:
            - 8080:8080
            
    backend:
        build:
            context: .
            dockerfile:
                DigiProd/Dockerfile
        ports:
            - 3000:3000
        links:
            - database:databaseURL
        depends_on:
            database:
                condition: service_healthy

    database:
        image: postgres:14.3
        environment:
            POSTGRES_USER: testUser
            POSTGRES_PASSWORD: testPW
            POSTGRES_DB: testDB
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
            interval: 30s
            timeout: 60s
            retries: 2
            start_period: 10s
